SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS TWEET;
DROP TABLE IF EXISTS USER_FOLLOWING;
DROP TABLE IF EXISTS USER;




/* Create Tables */

CREATE TABLE TWEET
(
	TWEET_ID bigint NOT NULL AUTO_INCREMENT,
	USER_ID bigint NOT NULL,
	CONTENTS varchar(140) NOT NULL,
	TWEET_DATETIME timestamp NOT NULL,
	PRIMARY KEY (TWEET_ID)
);


CREATE TABLE USER
(
	USER_ID bigint NOT NULL AUTO_INCREMENT,
	USER_NAME varchar(10) NOT NULL,
	PASSWORD varchar(20) NOT NULL,
	FAVORITE_ARTIST varchar(20) NOT NULL,
	REGISTER_DATETIME timestamp NOT NULL,
	PRIMARY KEY (USER_ID),
	UNIQUE (USER_NAME)
);


CREATE TABLE USER_FOLLOWING
(
	-- 
	-- 
	USER_FOLLOWING_ID bigint NOT NULL AUTO_INCREMENT COMMENT '
',
	FOLLOWER_USER_ID bigint NOT NULL,
	FOLLOWING_USER_ID bigint NOT NULL,
	PRIMARY KEY (USER_FOLLOWING_ID),
	UNIQUE (FOLLOWER_USER_ID, FOLLOWING_USER_ID)
);



/* Create Foreign Keys */

ALTER TABLE TWEET
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_FOLLOWING
	ADD FOREIGN KEY (FOLLOWER_USER_ID)
	REFERENCES USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_FOLLOWING
	ADD FOREIGN KEY (FOLLOWING_USER_ID)
	REFERENCES USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



